title: Welcome to my portfolio!
description: My portfolio and coding blog
author: vester
logo: /static/img/myface.png
github: https://github.com/pablovester
about: Front End Developer

baseurl: "testing"
url: "hola@pablovester.com.ar"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
